image: node:15.5.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run docs:build
  - npm run calendar:build

  artifacts:
    paths:
    - public
  
  only:
  - main
